resources:
- repo: self

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Use specific node version'
  inputs:
    version: '8.12.0'

# all envitonment variables should be defined in vsts UI
- script: |
    npm install -g npm@6.4.1
    npm update
    bash install.sh
    npm install -g typescript
    npm install -g gulp-cli
    npm install -g firebase-tools
    bash set-env.sh GITHUB_ACCESS_TOKEN FIREBASE_DEPLOY_TOKEN
      MAILER_HOST MAILER_PORT MAILER_EMAIL MAILER_CLIENT_ID MAILER_CLIENT_SECRET
      MAILER_REFRESH_TOKEN MAILER_ACCESS_TOKEN MAILER_RECIPIENT_EMAIL
    gulp compile-and-build
    rm ./.env ./functions/.env
    gulp client-unit-test
    firebase deploy --token $FIREBASE_DEPLOY_TOKEN
  env:
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)
    FIREBASE_DEPLOY_TOKEN: $(FIREBASE_DEPLOY_TOKEN)
    MAILER_HOST: $(MAILER_HOST)
    MAILER_PORT: $(MAILER_PORT)
    MAILER_EMAIL: $(MAILER_EMAIL)
    MAILER_CLIENT_ID: $(MAILER_CLIENT_ID)
    MAILER_CLIENT_SECRET: $(MAILER_CLIENT_SECRET)
    MAILER_REFRESH_TOKEN: $(MAILER_REFRESH_TOKEN)
    MAILER_ACCESS_TOKEN: $(MAILER_ACCESS_TOKEN)
    MAILER_RECIPIENT_EMAIL: $(MAILER_RECIPIENT_EMAIL)

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
