# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get yarn cache directory path and commit hash
        id: get-variables
        shell: bash
        run: echo "::set-output name=yarncachedir::$(yarn cache dir)"; echo "::set-output name=commitsha::$(echo ${GITHUB_SHA})"

      - name: Yarn/npm + Jest cache
        uses: actions/cache@v2
        id: workspace-cache # use this to check for `cache-hit` (`steps.workspace-cache.outputs.cache-hit != 'true'`)
        env:
          cache-name: workspace-cache
        with:
          path: |
            ~/.npm
            ${{ steps.get-variables.outputs.yarncachedir }}
            **/node_modules
            /tmp/jest_rs
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-workspace-${{ steps.get-variables.outputs.commitsha }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-workspace-
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install global dependencies
        run: npm i -g typescript @angular/cli firebase-tools @compodoc/ngd-cli

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --ignore-scripts && yarn ngcc

      - name: Lint
        run: ng lint

      - name: Unit test
        run: ng test --passWithNoTests --coverage=false --watch=false --maxWorkers=2 --ci --updateSnapshot

      - name: Set environment variables
        run: bash shell/set-env.sh $GITHUB_ACCESS_TOKEN $MAILER_HOST $MAILER_PORT $MAILER_EMAIL $MAILER_CLIENT_ID $MAILER_CLIENT_SECRET $MAILER_REFRESH_TOKEN $MAILER_ACCESS_TOKEN $MAILER_RECIPIENT_EMAIL
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          MAILER_HOST: ${{ secrets.MAILER_HOST }}
          MAILER_PORT: ${{ secrets.MAILER_PORT }}
          MAILER_EMAIL: ${{ secrets.MAILER_EMAIL }}
          MAILER_CLIENT_ID: ${{ secrets.MAILER_CLIENT_ID }}
          MAILER_CLIENT_SECRET: ${{ secrets.MAILER_CLIENT_SECRET }}
          MAILER_REFRESH_TOKEN: ${{ secrets.MAILER_REFRESH_TOKEN }}
          MAILER_ACCESS_TOKEN: ${{ secrets.MAILER_ACCESS_TOKEN }}
          MAILER_RECIPIENT_EMAIL: ${{ secrets.MAILER_RECIPIENT_EMAIL }}

      - name: Build
        run: ng build --prod

      - name: Deploy
        run: firebase deploy --only hosting --token "$FIREBASE_DEPLOY_TOKEN" || exit 1
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
